FreakLabMarket/FreakLabMarket/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

from django.conf.urls.static import static
from FreakLabMarket import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='goods')),
    path('user/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FreakLabMarket/goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'
urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('', views.catalog, name='catalog'),
    path('product/<slug:slug>', views.product, name='product'),
]

FreakLabMarket/main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

FreakLabMarket/users/urls.py
from tkinter.font import names

from django.urls import path
from users import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

FreakLabMarket/templates/base.html
<!DOCTYPE HTML>
<!--
	Phantom by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}
<html>
	<head>
		<title>Phantom by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/css/additional.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
                    {% include 'includes/header.html' %}

				<!-- Menu -->
					<nav id="menu">
						<h2>Menu</h2>
						<ul>
							<li><a href="{% url 'main:home' %}">Home</a></li>
							<li><a href="{% url 'main:about' %}">About</a></li>
							<li><a href="{% url 'goods:catalog' %}">catalog</a></li>
                            {% if user.is_admin or user.is_staff %}
							    <li><a href="{% url 'admin:index' %}">admin</a></li>
                            {% endif %} 
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'users:profile' %}">Profile</a></li>
                                <li><a href="{% url 'users:logout' %}">Logout</a></li>
                            {% else %}
                                <li><a href="{% url 'users:login' %}">Log in</a></li>
                                <li><a href="{% url 'users:registration' %}">Register</a></li>
                            {% endif %} 
                            

						</ul>
					</nav>

				<!-- Main -->
                    <div id="main">
                        <div class="inner">
                            {% block content %}

                            {% endblock %}
                        </div>
                    </div>

				<!-- Footer -->
                    {% include 'includes/footer.html' %}

			</div>

		<!-- Scripts -->
            <script src="{% static 'assets/js/dropdown.js' %}"></script>
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/notifications.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>
	</body>
</html>