FreakLabMarket/FreakLabMarket/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

from django.conf.urls.static import static
from FreakLabMarket import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='goods')),
    path('user/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FreakLabMarket/goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'
urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('', views.catalog, name='catalog'),
    path('product/<slug:slug>', views.product, name='product'),
]

FreakLabMarket/main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

FreakLabMarket/templates/includes/dropdown_filters.html
<div class="filters-container">
    <button class="filters-btn">Фильтры</button>
    <div class="filters-content">
        <form action="{% if request.GET.q %}{% url "goods:search" %}{% else %}{% url "goods:catalog" %}{% endif %}" id="filters-form" method="get">
            {% if request.GET.q %}
                <input type="hidden" name="q" value="{{ request.GET.q }}">
            {% endif %} 
            <div class="filter-section">
                <div class="filter-title">Категории</div>
                <div class="filter-options">
                    {% for category in categories %}
                        <label class="filter-option">
                            <input type="checkbox"
                                   id="{{ category.slug }}"
                                   name="category"
                                   value="{{ category.slug }}"
                                   {% if category.slug in applied_filters.selected_cats %}checked{% endif %}>
                            <span>{{ category.name }}</span>
                        </label>
                    {% endfor %}
                </div>
            </div>

            <div class="filter-section">
                <div class="filter-title">Цена</div>
                <div class="price-range">
                    <input type="number" class="price-input" id="price-from" name="price-from" placeholder="от" min="0" value="{{ applied_filters.min_value }}">
                    <span>-</span>
                    <input type="number" class="price-input" id="price-to" name="price-to" placeholder="до" min="0" value="{{ applied_filters.max_value }}">
                </div>
            </div>

            <div class="filter-actions">
                <button type="button" class="filter-action-btn reset" id="reset-btn">Сброс</button>
                <button type="submit" class="filter-action-btn apply">фильтр</button>
            </div>
        </form>
    </div>
</div>

FreakLabMarket/templates/includes/footer.html
<footer id="footer">
    <div class="inner">
        <section>
            <h2>Get in touch</h2>
            <form method="post" action="#">
                <div class="fields">
                    <div class="field half">
                        <input type="text" name="name" id="name" placeholder="Name" />
                    </div>
                    <div class="field half">
                        <input type="email" name="email" id="email" placeholder="Email" />
                    </div>
                    <div class="field">
                        <textarea name="message" id="message" placeholder="Message"></textarea>
                    </div>
                </div>
                <ul class="actions">
                    <li><input type="submit" value="Send" class="primary" /></li>
                </ul>
            </form>
        </section>
        <section>
            <h2>Follow</h2>
            <ul class="icons">
                <li><a href="#" class="icon brands style2 fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="icon brands style2 fa-facebook-f"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon brands style2 fa-instagram"><span class="label">Instagram</span></a></li>
                <li><a href="#" class="icon brands style2 fa-dribbble"><span class="label">Dribbble</span></a></li>
                <li><a href="#" class="icon brands style2 fa-github"><span class="label">GitHub</span></a></li>
                <li><a href="#" class="icon brands style2 fa-500px"><span class="label">500px</span></a></li>
                <li><a href="#" class="icon solid style2 fa-phone"><span class="label">Phone</span></a></li>
                <li><a href="#" class="icon solid style2 fa-envelope"><span class="label">Email</span></a></li>
            </ul>
        </section>
        <ul class="copyright">
            <li>&copy; Untitled. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>
    </div>
</footer>

FreakLabMarket/templates/includes/header.html
{% load static %}

<header id="header">
    <div class="inner">

        <!-- Logo -->
            <a href="{% url 'main:home' %}" class="logo">
                <span class="symbol"><img src="{% static 'images/logo.svg' %}" alt="" /></span><span class="title">Phantom</span>
            </a>

        <!-- Nav -->
            <nav>
                <ul>
                    <li><a href="#menu">Menu</a></li>
                </ul>
            </nav>

    </div>
</header>