FreakLabMarket/FreakLabMarket/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

from django.conf.urls.static import static
from FreakLabMarket import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='goods')),
    path('user/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FreakLabMarket/main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

FreakLabMarket/users/urls.py
from tkinter.font import names

from django.urls import path
from users import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

FreakLabMarket/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to="users_images", blank=True, null=True, verbose_name='Аватар')
    background_image = models.ImageField(upload_to="users_bg_images", blank=True, null=True, verbose_name='Обложка')
    bio = models.CharField(blank=True, default='', null=True, max_length=1000, verbose_name='Описание пользователя')
    newsletter = models.BooleanField(default=False, verbose_name='Новости')
    notifications = models.BooleanField(default=False, verbose_name='Оповещения')

    class Meta:
        db_table = 'users'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

FreakLabMarket/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(
        widget=forms.TextInput(attrs={"autofocus": True,
                                      'placeholder': 'Username or Email',}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
                                      'placeholder': 'Password',}))

    class Meta:
        model = User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
            'bio',
        ]
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    bio = forms.Textarea()


class ProfileForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('password', None)

    class Meta:
        model = User
        fields = [
            'image',
            # 'background_image',
            'first_name',
            'last_name',
            'username',
            'email',
            'bio',
            'newsletter',
            'notifications',
        ]
    # image = forms.ImageField(required=False)
    # background_image = forms.ImageField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    bio = forms.CharField(widget=forms.Textarea(attrs={'required': False,}))
    newsletter = forms.CheckboxInput()
    notifications = forms.CheckboxInput()

FreakLabMarket/users/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from users.forms import UserLoginForm, UserRegisterForm, ProfileForm


def login(request):
    # form = UserLoginForm(request.POST or None)
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)

                if request.POST.get('next', None):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('main:home'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Login',
         'form': form,
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main:home'))
    else:
        form = UserRegisterForm()
    context = {
        'title': 'registration',
        'form': form,
    }
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
        print("Form errors:", form.errors)
        print("Non-field errors:", form.non_field_errors())
    else:
        form = ProfileForm(instance=request.user)

    context = {
        'title': 'profile',
        'form': form,
    }
    return render(request, 'users/profile.html', context)


@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse('main:home'))

FreakLabMarket/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<h1>Sign In</h1>
    <p>Welcome back! Please sign in to your account.</p>

    <!-- Login Form -->
        <section>
            <h2>Login Form</h2>
            <form method="post" action="{% url "users:login" %}">
                {% csrf_token %}
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %} 
                <div class="row gtr-uniform">
                    <div class="col-12">
                        {{ form.username }}
                    </div>
                    <div class="col-12">
                        {{ form.password }}
                    </div>
                    <div class="col-6 col-12-small">
                        <input type="checkbox" id="demo-remember" name="demo-remember" checked>
                        <label for="demo-remember">Remember me</label>
                    </div>
                    <div class="col-6 col-12-small">
                        <a href="#" class="button small fit">Forgot Password?</a>
                    </div>
                    <div class="col-12">
                        <ul class="actions">
                            <li><input type="submit" value="Sign In" class="primary" /></li>
                            <li><input type="reset" value="Clear" /></li>
                        </ul>
                    </div>
                    <div class="col-12">
                        <p>Don't have an account? <a href="{% url 'users:registration' %}">Register here</a>.</p>
                    </div>
                </div>
            </form>
        </section>

    <!-- Social Login -->
        <section>
            <h3>Or sign in with</h3>
            <ul class="icons">
                <li><a href="#" class="icon brands style2 fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="icon brands style2 fa-facebook-f"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon brands style2 fa-google"><span class="label">Google</span></a></li>
                <li><a href="#" class="icon brands style2 fa-github"><span class="label">GitHub</span></a></li>
            </ul>
        </section>

{% endblock %}

FreakLabMarket/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<header>
        <h1>User Profile</h1>
        <p>Manage your account settings and preferences.</p>
    </header>

    <!-- Profile Header -->
    <form method="post" action="{% url 'users:profile' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <section>
{#            <div class="box alt">#}
{#                <div class="row gtr-uniform">#}
{#                    <div class="col-12">#}
{#                        <span class="image fit"><img src="/media/goods_images/pic13.jpg" alt="" /></span>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
            
            <div class="row">

                <div class="col-4 col-12-medium">

                    <span class="image fit">
                        {% if user.image %}
                            <img src="{{ user.image.url }}" alt="Profile Picture" class="profile-pic" />
                        {% else %}
                            <img src="/media/goods_images/pic15.jpg" alt="Profile Picture" class="profile-pic" />
                        {% endif %}
                    </span>
                    <ul class="actions">

                        <li><label for="id_image" class="button primary fit">
                            <span class="file-icon">📁</span>
                            <span class="file-text" id="file-status">Выберите файл</span>
                        </label>
                            <input type="file"
                                   class=""
                                   id="id_image"
                                   name="image"
                                   accept="image/*"
                                   onchange="document.getElementById('file-status').textContent = this.files[0] ? '✓ Файл выбран' : 'Файл не выбран'"
                                   style="display: none;"
                            ></li>
                    </ul>
                    {% if form.image.errors %}
                        <div class="align-center">{{ form.image.errors }}</div>
                    {% endif %}


                </div>

                <div class="col-8 col-12-medium">

                    <h2>{{ form.first_name.value }} {{ form.last_name.value }} aka. {{ form.username.value }}</h2>


                    <div class="col-12 col-12-medium">
                        <input type="text"
                               name="first_name"
                               id="id_first_name"
                               value="{{ form.first_name.value }}"
                               placeholder="First name" required/>
                        {% if form.first_name.errors %}
                            <div class="align-center">{{ form.first_name.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="col-12 col-12-medium">
                        <input type="text"
                               name="last_name"
                               id="id_last_name"
                               value="{{ form.last_name.value }}"
                               placeholder="Last name" required/>
                        {% if form.last_name.errors %}
                            <div class="align-center">{{ form.last_name.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="col-12 col-12-medium">
                        <input type="text"
                               name="username"
                               id="id_username"
                               value="{{ form.username.value }}"
                               placeholder="Username" required/>
                        {% if form.username.errors %}
                            <div class="align-center">{{ form.username.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="col-12 col-12-medium">
                        <input type="email"
                               name="email"
                               id="id_email"
                               value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                               placeholder="Email" required/>
                        {% if form.username.errors %}
                            <div class="align-center">{{ form.email.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-12">
                        <textarea name="bio"
                                  id="id_bio"
                                  placeholder="Tell us about yourself (optional)"
                                  rows="3">
                            {{ form.bio.value }}
                        </textarea>
                    </div>

{#                    <p><strong>Bio:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>#}
                    
{#                    <ul class="actions">#}
{#                        <li><a href="#" class="button primary">Edit Profile</a></li>#}
{#                        <li><a href="#" class="button">Change Password</a></li>#}
{#                    </ul>#}
                </div>
            </div>
        </section>

    <!-- Preferences -->
        <section>
            <h2>Additional settings</h2>
            <div class="row gtr-uniform">
                <div class="col-6 col-12-small">
                    <input type="checkbox"
                           id="id_newsletter"
                           name="newsletter"
                           {% if form.newsletter.value %}checked{% endif %}>
                    <label for="id_newsletter">Email Newsletter</label>
                </div>
                <div class="col-6 col-12-small">
                    <input type="checkbox"
                           id="id_notifications"
                           name="notifications"
                           {% if form.notifications.value %}checked{% endif %}>
                    <label for="id_notifications">Push Notifications</label>
                </div>
                <div class="col-12">
                    <ul class="actions">
                        <li><input type="submit" value="Save Preferences" class="primary" /></li>
                        <li><input type="reset" value="Reset" /></li>
                    </ul>
                </div>
            </div>
        </section>
    </form>
{% endblock %}

FreakLabMarket/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<h1>Create Account</h1>
    <p>Join our community by creating a new account.</p>

    <!-- Registration Form -->
        <section>
            <h2>Registration Form</h2>
            <form method="post" action="{% url "users:registration" %}">
                {% csrf_token %}
                <div class="row gtr-uniform">
                    <div class="col-6 col-12-xsmall">
                        <input type="text" 
                               name="first_name" 
                               id="id_first_name" 
                               value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" 
                               placeholder="First Name" />
                        {% if form.first_name.errors %}
                            <div class="fa-red-river">{{ form.first_name.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-6 col-12-xsmall">
                        <input type="text" 
                               name="last_name" 
                               id="id_last_name" 
                               value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" 
                               placeholder="Last Name" />
                        {% if form.last_name.errors %}
                            <div class="fa-red-river">{{ form.last_name.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-12">
                        <input type="text" 
                               name="username" 
                               id="id_username" 
                               value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                               placeholder="Username" required/>
                        {% if form.username.errors %}
                            <div class="fa-red-river">{{ form.username.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-12">
                        <input type="email" 
                               name="email" 
                               id="id_email" 
                               value="{% if form.email.value %}{{ form.email.value }}{% endif %}" 
                               placeholder="Email Address" required/>
                        {% if form.email.errors %}
                            <div class="fa-red-river">{{ form.email.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-6 col-12-xsmall">
                        <input type="password" 
                               name="password1" 
                               id="id_password1" 
                               value="" 
                               placeholder="Password" required/>
                        {% if form.password1.errors %}
                            <div class="fa-red-river">{{ form.password1.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-6 col-12-xsmall">
                        <input type="password" 
                               name="password2" 
                               id="id_password2" 
                               value="" 
                               placeholder="Confirm Password" required/>
                        {% if form.password2.errors %}
                            <div class="fa-red-river">{{ form.password2.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="col-12">
                        <textarea name="bio" 
                                  id="id_bio" 
                                  placeholder="Tell us about yourself (optional)"
                                  value="{% if form.bio.value %}{{ form.bio.value }}{% endif %}"
                                  rows="3"></textarea>
                    </div>
                    <div class="col-6 col-12-small">
                        <input type="checkbox" id="demo-terms" name="demo-terms">
                        <label for="demo-terms">I agree to the <a href="#">Terms and Conditions</a></label>
                    </div>
                    <div class="col-6 col-12-small">
                        <input type="checkbox" id="demo-newsletter" name="demo-newsletter" checked>
                        <label for="demo-newsletter">Subscribe to newsletter</label>
                    </div>
                    <div class="col-12">
                        <ul class="actions">
                            <li><input type="submit" value="Create Account" class="primary" /></li>
                            <li><input type="reset" value="Reset" /></li>
                        </ul>
                    </div>
                    <div class="col-12">
                        <p>Already have an account? <a href="{% url 'users:login' %}">Sign in here</a>.</p>
                    </div>
                </div>
            </form>
        </section>

{% endblock %}