FreakLabMarket/FreakLabMarket/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

from django.conf.urls.static import static
from FreakLabMarket import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='goods')),
    path('user/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FreakLabMarket/goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'
urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('', views.catalog, name='catalog'),
    path('product/<slug:slug>', views.product, name='product'),
]

FreakLabMarket/main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

FreakLabMarket/goods/models.py
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=250, unique=True, blank=True, null=True, verbose_name="URL")

    __str__ = lambda self : self.name

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'


class Products(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=250, unique=True, blank=True, null=True, verbose_name="URL")
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Скидка %')
    quantity = models.PositiveIntegerField(default=0.00, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name="Категория")

    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ("id",)

    __str__ = lambda self: f'{self.name} - Количество: {self.quantity}'

FreakLabMarket/goods/views.py
from re import search

from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.db.models import Q

from django.shortcuts import render
from select import select

from goods.models import Products, Categories
from django.core.paginator import Paginator


def catalog(request):
    goods = Products.objects.all()
    categories = Categories.objects.all()

    filtered_goods, applied_filters = set_filter_settings(request, goods)
    current_page = get_current_page(request, filtered_goods)

    context = {
        'goods': current_page,
        'categories': categories,
        'applied_filters': applied_filters,
    }
    return render(request, "goods/catalog.html", context)


def set_filter_settings(request, goods):
    selected_cats = request.GET.getlist('category', None)
    min_value = request.GET.get('price-from', None)
    max_value = request.GET.get('price-to', None)
    query = request.GET.get('q', None)
    applied_filters = dict()

    if selected_cats and 'all' not in selected_cats:
        goods = goods.filter(category__slug__in=selected_cats)

    if query:
        goods = q_search(goods, query)

    if selected_cats:
        applied_filters['selected_cats'] = selected_cats

    if min_value:
        goods = goods.filter(price__gte=min_value)
        applied_filters['min_value'] = min_value

    if max_value:
        goods = goods.filter(price__lte=max_value)
        applied_filters['max_value'] = max_value


    return goods, applied_filters


def q_search(goods, query):
    if query.isdigit() and len(query) <= 5:
        return goods.filter(id=int(query))

    vector = SearchVector("name", "description")
    query = SearchQuery(query)
    return goods.annotate(rank=SearchRank(vector, query)).filter(rank__gt=0).order_by('-rank')


def get_current_page(request, goods):
    page = request.GET.get('page', 1)
    paginator = Paginator(goods, 3)
    return paginator.page(page)


def product(request, slug):
    prod = Products.objects.get(slug=slug)
    context = {
        'good': prod
    }

    return render(request, "goods/product.html", context=context)

FreakLabMarket/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}

{% block content %}
    <header>
        <h1>This is our catalog<br />
        choose what you desire.</h1>
{#        <p>Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.</p>#}
    </header>

    {% if request.GET.q %}
        
        <h2>результаты по запросу: {{ request.GET.q }}</h2>
        {% if not goods %}
            <h4>По запросу ничего не найдено</h4>
        {% endif %} 
    {% endif %} 

    <div class="row gtr-uniform">
        <div class="col-2 col-6-medium col-6-small">
            {% include 'includes/dropdown_filters.html' %}
        </div>
        <div class="col-10 col-6-medium">
            <form method="get" action="{% url 'goods:search' %}">
                <input type="text" name="q" id="seach-textarea" value="" placeholder="Search"/>
            </form>
        </div>
    </div>
    <br>

    
    <section class="tiles">
        {% for good in goods %}
            <article class="style7">
                <span class="image">
                    <img src="{{ good.image.url }}" alt="" />
                </span>
                <a href="{% url 'goods:product' good.slug %}">
                    <h2>{{ good.name }}</h2>
                    <div class="content">
                        <p>{{ good.description|truncatechars:150 }}<br/>{{ good.price }}</p>
                    </div>
                </a>
            </article>
        {% endfor %}
    </section>
    {% if goods %}
            <br><br><br><br><br><br><br>
    <section>
        <ul class="actions">
            <li><a href="#" class="button primary">pagination</a></li>

            {% if goods.has_previous %}
                <li><a href="{% compile_url page=goods.previous_page_number %}" class="button">previous</a></li>
            {% else %}
                <li><a href="#" class="button disabled">previous</a></li>
            {% endif %}
            {% if goods.has_next %}
                <li><a href="{% compile_url page=goods.next_page_number %}" class="button">next</a></li>
            {% else %}
                <li><a href="#" class="button disabled">next</a></li>
            {% endif %}

            <li><a href="#" class="button primary">page: {{ goods.number }}</a></li>
        </ul>
    </section>
    {% endif %} 
    
{% endblock %}

FreakLabMarket/templates/goods/product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div id="main">
        <div class="inner">
            <h1>{{ good.name }}</h1>

<!--            <span class="image main"><img src="{{ good.image.url }}" alt="" /></span>-->
            <span class="image left">
                <img src="{{ good.image.url }}" alt="">
            </span>
            <p>{{ good.description }}</p>
            <div>{{ good.id }}</div>
        </div>
    </div>
{% endblock %}